### ISSUE TITLE
Errors while testing dggs.py

### ISSUE THREAD

**Issue by yaduart** [ANU-Linked-Earth-Data/dggs#1]
[yxs659@raijin4 tests]$ python3 test_dggs.py
Traceback (most recent call last):
  File "test_dggs.py", line 19, in <module>
    from numpy import array, pi, sin, cos, tan, arctan, arcsin
  File "/home/659/yxs659/.local/lib/python3.4/site-packages/numpy/**init**.py", line 180, in <module>
    from . import add_newdocs
  File "/home/659/yxs659/.local/lib/python3.4/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/659/yxs659/.local/lib/python3.4/site-packages/numpy/lib/**init**.py", line 8, in <module>
    from .type_check import *
  File "/home/659/yxs659/.local/lib/python3.4/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/659/yxs659/.local/lib/python3.4/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: /home/659/yxs659/.local/lib/python3.4/site-packages/numpy/core/multiarray.cpython-34m.so: undefined symbol: _intel_fast_memset

**Comment by yaduart** [comment]
I used virtual environment but still getting the same error.
Well, it happens when you try to import pyproj.
I have raised an issue on the pyproj repository.

Error while importing pyproj #76 
https://github.com/jswhit/pyproj/issues/76

**Comment by yaduart** [comment]
It seems to work when gcc is used to install the package.

CC=gcc pip3 install pyproj
